version: '3.5'

services:
  gh-stats:
    image: esumitra/github-stats-service:0.1.0-SNAPSHOT
    hostname: gh-stats
    expose:
      - "8080"
    environment:
      - GH_API_KEY=xxx
      - ENVIRONMENT=dev

  nginx:
      image: nginx:latest
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
      depends_on:
        - gh-stats
      ports:
        - "4000:4000"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus-config.yml:/etc/prometheus/prometheus.yml
#      - prom_data:/prometheus

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./grafana-config.yml:/etc/grafana/provisioning/datasources/datasource.yml
      
networks:
  default:
    name: ghstats-network