version: '3.5'

services:
  gh-stats:
    image: esumitra/github-stats-service:0.1.0-SNAPSHOT
    hostname: gh-stats
    expose:
      - "8080"
    environment:
      - GH_API_KEY=xxx
      - ENVIRONMENT=dev

  nginx:
      image: nginx:latest
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
      depends_on:
        - gh-stats
      ports:
        - "4000:4000"

networks:
  default:
    name: ghstats-network